### ISSUE TITLE
Fix contrast issues

### ISSUE THREAD

**Issue by Twoos123** [Twoos123/asadali-portfolio#6]
![Image](https://github.com/Twoos123/asadali-portfolio/assets/54924158/6d7d8690-3651-4170-aa29-5576676b7afd)

![Image](https://github.com/Twoos123/asadali-portfolio/assets/54924158/22431ba5-f195-473b-b781-2b4b27dbf6fe)

**Comment by MFarabi619** [comment]
![Image](https://github.com/Twoos123/asadali-portfolio/assets/54924158/0c0dfb53-3f75-45f3-a56e-e20f31dcf6bf)
