### ISSUE TITLE
Fix CLS issues

### ISSUE THREAD

**Issue by Twoos123** [Twoos123/asadali-portfolio#7]

**Comment by MFarabi619** [comment]
When you click one of these, the rest of the cards move.

![Image](https://github.com/Twoos123/asadali-portfolio/assets/54924158/0cf34f9a-688e-48b9-98ad-14fe0fda2f7c)

This is called [Cumulative layout shift](https://web.dev/articles/cls) and is a big no-no for web dev UX. Explore different ideas. Don't make elements move unexpectedly like this. Unlike an accordion element, there is no hint to the user of impending movement.
